# this is the file used in outomatinc deployments
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: devops/hooks/BeforeInstallScript.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: devops/hooks/AfterInstallScript.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: devops/hooks/start_server.sh
      timeout: 120
      runas: root
  ApplicationStop:
    - location: devops/hooks/stop_server.sh
      timeout: 120
      runas: root
